export const ERROR_CODES = {
  // Erros de negócio

  // ANIMAIS
  ANIMAL_UNAVAILABLE: 'ANIMAL_UNAVAILABLE',
  ANIMAL_NOT_FOUND: 'ANIMAL_NOT_FOUND',
  ANIMALS_NOT_FOUND: 'ANIMALS_NOT_FOUND',
  UNABLE_TO_GET_ANIMAL: 'UNABLE_TO_GET_ANIMAL',
  UNABLE_TO_GET_ANIMALS: 'UNABLE_TO_GET_ANIMALS',

  UNABLE_TO_GET_SPECIES: 'UNABLE_TO_GET_SPECIES',
  UNABLE_TO_GET_BREEDS: 'UNABLE_TO_GET_BREEDS',

  // DEWORMING
  UNABLE_TO_GET_DEWORMING: 'UNABLE_TO_GET_DEWORMING',

  // VACINAS
  UNABLE_TO_GET_VACCINE: 'UNABLE_TO_GET_VACCINE',

  // VET APPOINTMENT
  UNABLE_TO_GET_VET_APPT: 'UNABLE_TO_GET_VET_APPT',

  // CUIDADOS
  UNABLE_TO_GET_CARE_RECORDS: 'UNABLE_TO_GET_CARE_RECORDS',

  // ADOÇÕES
  ADOPTION_FAILED: 'ADOPTION_FAILED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  UNABLE_TO_GET_ADOPTION: 'UNABLE_TO_GET_ADOPTION',
  UNABLE_TO_GET_ADOPTIONS: 'UNABLE_TO_GET_ADOPTIONS',

  // ADOTANTES
  ADOPTER_FLAGGED: 'ADOPTER_FLAGGED',
  ADOPTERS_EMAIL_SCOPE_OUTDATED: 'ADOPTERS_EMAIL_SCOPE_OUTDATED',
  ADOPTERS_SCHEMA_OUTDATED: 'ADOPTERS_SCHEMA_OUTDATED',
  UNABLE_TO_GET_ADOPTER: 'UNABLE_TO_GET_ADOPTER',
  UNABLE_TO_GET_ADOPTERS: 'UNABLE_TO_GET_ADOPTERS',

  // REGISTO
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ORGANIZATION_ALREADY_EXISTS: 'ORGANIZATION_ALREADY_EXISTS',

  // AUTENTICAÇÃO
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',

  // GENÉRICOS
  DB_ERROR: 'DB_ERROR',
  DB_ERROR_UPDATE: 'DB_ERROR_UPDATE',
  NOT_FOUND: 'NOT_FOUND',
  UNKNOWN: 'UNKNOWN',
  INVALID_CHANGE: 'INVALID_CHANGE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
